---
- name: Install Node.js on Web Server (Amazon Linux 2 method)
  hosts: web
  become: yes

  tasks:
    - name: Enable NodeJS 16 from Amazon Linux Extras
      shell: amazon-linux-extras enable nodejs16
      args:
        executable: /bin/bash

    - name: Install NodeJS
      yum:
        name: nodejs
        state: present
